// <auto-generated />
namespace ADI_FORMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DropLifespanInAVD : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropLifespanInAVD));
        
        string IMigrationMetadata.Id
        {
            get { return "201909261349016_DropLifespanInAVD"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
