// <auto-generated />
namespace ADI_FORMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AnyUpd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AnyUpd));
        
        string IMigrationMetadata.Id
        {
            get { return "201909151222373_AnyUpd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
